<?php

namespace Magend\MagzineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MagzineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagzineRepository extends EntityRepository
{
}