<?php

namespace Magend\MagazineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MagazineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazineRepository extends EntityRepository
{
}