imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: zh }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: zh
        # lifetime:       86400 #one day
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    
services:
    twig.extension.txt:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    pagerfanta.view.magend:
        class: Pagerfanta\View\OptionableView
        arguments:
            - @pagerfanta.view.default
            - { proximity: 3, previous_message: ←, next_message: → }
        public: false
        tags: [{ name: pagerfanta.view, alias: magend }]

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        #   yui_css:
        #       jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        #   yui_js:
        #       jar: %kernel.root_dir%/Resources/java/yuicompressor.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
    
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: Magend\UserBundle\Entity\User
    #from_email:
    #    address: admin@paiqoo.com
    #    sender_name: Paiqoo Admin
    #registration:
    #    form:
    #        type: pq_user_registration
    #        handler: pq.registration.form.handler
    #    confirmation:
    #        enabled: false

avalanche_imagine:
    filters:
        landscapeThumb:
            type:    thumbnail
            options: { size: [205, 154], mode: outbound }
        portraitThumb:
            type:    thumbnail
            options: { size: [96, 128], mode: outbound }
            
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR]
            ADMIN:    [MASTER]
    title: iMagShow
    #title_logo: images/logo_black.gif
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
            # Customize this part to add new block configuration
            - { position: right, type: sonata.block.service.text, settings: { content: "欢迎使用iMagShow后台"} }
            #- { position: right, type: pq.sonata.block.service.stats }
        #groups:
        #    user_admin:
        #        label: 用户
        #        items: [pq.user.admin.user]
