MagendDevBundle:
    resource: "@MagendDevBundle/Controller/"
    type:     annotation
    prefix:   /

MagendIAPBundle:
    resource: "@MagendIAPBundle/Controller/"
    type:     annotation
    prefix:   /

MagendOperationBundle:
    resource: "@MagendOperationBundle/Controller/"
    type:     annotation
    prefix:   /

MagendNewsBundle:
    resource: "@MagendNewsBundle/Controller/"
    type:     annotation
    prefix:   /

MagendBackendBundle:
    resource: "@MagendBackendBundle/Controller/"
    type:     annotation
    prefix:   /

MagendVersionBundle:
    resource: "@MagendVersionBundle/Controller/"
    type:     annotation
    prefix:   /

MagendAssetBundle:
    resource: "@MagendAssetBundle/Controller/"
    type:     annotation
    prefix:   /

MagendOutputBundle:
    resource: "@MagendOutputBundle/Controller/"
    type:     annotation
    prefix:   /

MagendProjectBundle:
    resource: "@MagendProjectBundle/Controller/"
    type:     annotation
    prefix:   /

MagendHotBundle:
    resource: "@MagendHotBundle/Controller/"
    type:     annotation
    prefix:   /

MagendUserBundle:
    resource: "@MagendUserBundle/Controller/"
    type:     annotation
    prefix:   /

MagendFeedbackBundle:
    resource: "@MagendFeedbackBundle/Controller/"
    type:     annotation
    prefix:   /

MagendBaseBundle:
    resource: "@MagendBaseBundle/Controller/"
    type:     annotation
    prefix:   /

MagendInstituteBundle:
    resource: "@MagendInstituteBundle/Controller/"
    type:     annotation
    prefix:   /

MagendMagazineBundle:
    resource: "@MagendMagazineBundle/Controller/"
    type:     annotation
    prefix:   /

MagendHomeBundle:
    resource: "@MagendHomeBundle/Controller/"
    type:     annotation
    prefix:   /

MagendKeywordBundle:
    resource: "@MagendKeywordBundle/Controller/"
    type:     annotation
    prefix:   /

MagendArchitectBundle:
    resource: "@MagendArchitectBundle/Controller/"
    type:     annotation
    prefix:   /

MagendPageBundle:
    resource: "@MagendPageBundle/Controller/"
    type:     annotation
    prefix:   /

MagendArticleBundle:
    resource: "@MagendArticleBundle/Controller/"
    type:     annotation
    prefix:   /

MagendIssueBundle:
    resource: "@MagendIssueBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /account
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_imagine:
    resource: .
    type:     imagine
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

backend_user:
    resource: '@MagendBackendBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin