security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            providers: [mag_bundle, in_memory]
        mag_bundle:
            id: magend.user_manager
        in_memory:
            users:
                Erick:  { password: 5dscape2011, roles: [ 'ROLE_ADMIN' ] }
                Kail: { password: 5dscape2011, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        main:
            pattern: ^/
            provider: chain_provider
            form_login:
                always_use_default_target_path: true
                default_target_path: /dashboard
            logout: true
            anonymous: true
            remember_me:
                key:      this_is_secret_ingredient_from_iMagShow
                lifetime: 2592000 # 30days
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*, roles: ROLE_ADMIN }
