security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_CORP:        ROLE_USER
        ROLE_ADMIN:       ROLE_USER, ROLE_CORP
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are not using acl then this line must be uncommented

    providers:
        mag_bundle:
            id: magend.user_manager

    firewalls:
        main:
            pattern: ^/
            provider: mag_bundle
            form_login:
                always_use_default_target_path: true
                default_target_path: /dashboard
            logout: true
            anonymous: true
            remember_me:
                key:      this_is_secret_ingredient_from_iMagShow
                lifetime: 2592000 # 30days
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/corp/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # first matched rules apply
        - { path: ^/access, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/output, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/article/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/admin/, role: ROLE_ADMIN }
        
        - { path: ^/.*, role: ROLE_CORP }
