<?php

namespace Magend\ArchitectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArchitectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchitectRepository extends EntityRepository
{
    /**
     * Convert array of string to array of entities
     * 
     * @param Array $architects
     * @return array
     */
    public function toEntities(Array $architects)
    {
        $entities = $this->findBy(array('name'=>$architects));
        $existingAts = array();
        foreach ($entities as $entity) {
            $existingAts[] = $entity->getName();
        }
        
        foreach ($architects as $at) {
            if (!in_array($at, $existingAts)) {
                $entities[] = new Architect($at);
            }
        }
        
        return $entities;
    }
}